version: '3.4'
volumes:
  env:

services:
  thermostat.emulator:
    image: ${DOCKER_REGISTRY}thermostatemulator
    build:
      context: .
      dockerfile: Thermostat.Emulator/Dockerfile
    volumes:
    - env:/env


  normalizetemperaturemodule:  
    image: ${DOCKER_REGISTRY}normalizetemperaturemodule
    build:
      context: .
      dockerfile: Modules/NormalizeTemperatureModule/Dockerfile
    volumes:
    - env:/env
        
  temperaturemodule:
    image: ${DOCKER_REGISTRY}temperaturemodule
    build:
      context: .
      dockerfile: Modules/TemperatureModule/Dockerfile
    volumes:
    - env:/env
