version: '3.4'

services:

  normalizetemperaturemodule:
    image: ${DOCKER_REGISTRY}normalizetemperaturemodule
    build:
      context: .
      dockerfile: Example/Modules/NormalizeTemperatureModule/Dockerfile

       
  temperaturemodule:
    image: ${DOCKER_REGISTRY}temperaturemodule
    build:
      context: .
      dockerfile: Example/Modules/TemperatureModule/Dockerfile


  thermostat.emulator:
    image: ${DOCKER_REGISTRY}thermostatemulator
    build:
      context: .
      dockerfile: Example/Thermostat.Emulator/Dockerfile

