version: '3.4'

services:
  TypeEdgeApplication.Emulator:
    image: ${DOCKER_REGISTRY}emulatorimage
    build: 
      context: .
      dockerfile: TypeEdgeApplication.Emulator/Dockerfile
    volumes:
    - env:/env