version: '3.4'
      
services:
  TypeEdgeApplication.Emulator:
    image: ${DOCKER_REGISTRY}TypeEdgeApplicationEmulatorImageName
    build: 
      context: .
      dockerfile: TypeEdgeApplication.Emulator/DockerfileEmpty

  TypeEdgeModule1:
    image: ${DOCKER_REGISTRY}TypeEdgeModule1ImageName
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule1/Dockerfile

  TypeEdgeModule2:
    image: ${DOCKER_REGISTRY}TypeEdgeModule2ImageName   
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule2/Dockerfile


