version: '3.4'
volumes:
  env:
      
services:
  emulatorimage:
    image: ${DOCKER_REGISTRY}emulatorimage
    build: 
      context: .
      dockerfile: TypeEdgeApplication.Emulator/DockerfileEmpty
    volumes:
    - env:/app/env

  module1image:
    image: ${DOCKER_REGISTRY}module1image
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule1/Dockerfile
    volumes:
    - env:/app/env

  module2image:
    image: ${DOCKER_REGISTRY}module2image   
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule2/Dockerfile
    volumes:
    - env:/app/env

