version: '3.4'
volumes:
  env:
      
services:
  emulatorimage:
    image: ${DOCKER_REGISTRY}emulatorimage
    build: 
      context: .
      dockerfile: TypeEdgeML.Emulator/DockerfileEmpty
    volumes:
    - env:/env

  module1image:
    image: ${DOCKER_REGISTRY}module1image
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule1/Dockerfile
    volumes:
    - env:/env

  module2image:
    image: ${DOCKER_REGISTRY}module2image   
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule2/Dockerfile
    volumes:
    - env:/env

  module3image:
    image: ${DOCKER_REGISTRY}module3image   
    build:
      context: .
      dockerfile: Modules/TypeEdgeModule3/Dockerfile
    volumes:
    - env:/env